version: '2'
services:
  redis:
    image: "redis"
  postgres:
    image: "postgres:latest"
    environment:
     POSTGRES_PASSWORD: 123
     POSTGRES_USER: katietruong
  web:
    build: .
    ports:
     - "80:7777"
    volumes:
     - .:/usr/src/app
    depends_on:
      - postgres
      - redis
    # command: ["./wait_for_it.sh", "postgres:5432", "--", "npm", "start"]